name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  buildAndRun:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v2.1.4

      - name: Tests
        run: deno test
      
      - name: Build Deno App
        run: deno compile --allow-read --allow-env --allow-write --allow-run --output ./dist/disconnected index.ts

      - name: Extract the tag name
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Tag name: $TAG_NAME"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: "Release $env.TAG_NAME" # Replace with your desired release name
          body: Working with switch-client and updating action to run on tag push
          draft: false
          prerelease: false
          
      - name: Upload Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/disconnected
          asset_name: disconnected
          asset_content_type: application/octet-stream
