# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Build and Release

on:
  push:
    branches: ["master"]

jobs:
  buildAndRun:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.26

      - name: Tests
        run: deno test
      
      - name: Build Deno App
        run: deno compile --allow-read --allow-env --allow-write --allow-run --output ./dist/disconnected index.ts
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: v0.2.2 # Replace with your desired tag name
          release_name: Release 0.2.2 # Replace with your desired release name
          body: |
            Fixed [issue](https://github.com/austinwilcox/disconnected/issues/5) with error message appearing when no active tmux sessions are running.

            I have also added some basic tests and an interface for some of the tmux commands, these tests will also run as part of the build and release process.
          draft: false
          prerelease: false
          
      - name: Upload Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/disconnected
          asset_name: disconnected
          asset_content_type: application/octet-stream
