name: Mirror

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror
      uses: austinwilcox/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/austinwilcox21/disconnected"
      env:
        FOLLOW_TAGS: "false"
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "austinwilcox21"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
